AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dd_app

  Sample SAM Template for dd_app

Parameters:
  AppKey: 
    Type: String
  ApiKey:
    Type: String
  Email:
    Type: String
  TeamName:
    Type: String

Resources:
  Functions:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: Functions
      Handler: function.DataDog::handleRequest
      Runtime: java8
      MemorySize: 512
      Timeout: 60
      Architectures:
        - x86_64
      Policies:
        - AmazonDevOpsGuruReadOnlyAccess
      Environment:
        Variables:
          DD_APP_KEY: !Ref AppKey
          DD_API_KEY: !Ref ApiKey
          EMAIL: !Ref Email
          TEAM_NAME: !Ref TeamName
      Events:
        InsightOpen:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.devops-guru"
              detail-type: 
                - "DevOps Guru New Insight Open"
        NewAnomaly:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.devops-guru"
              detail-type: 
                - "DevOps Guru New Anomaly Association"
        NewRecommendations:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.devops-guru"
              detail-type: 
                - "DevOps Guru New Recommendation Created"
        InsightClosed:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.devops-guru"
              detail-type: 
                - "DevOps Guru Insight Closed"
        SeverityUpgraded:
          Type: EventBridgeRule
          Properties:
            Pattern:
              source: 
                - "aws.devops-guru"
              detail-type: 
                - "DevOps Guru Insight Severity Upgraded"